#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run prettier
git add '*.ts'

find . -type d -name 'node_modules' -prune -false -o -name '.webpack' -prune -false -o -type f -name 'yarn.lock' | sort | xargs shasum > modules-sha && git add modules-sha
